### ISSUE TITLE
Inkscape menampilkan dokumen baru (dokumen kosong) daripada file yang dipilih. Kalau di uninstall scriptnya, Inkscape tidak bisa dibuka. Bisa dibuka lewat terminal

### ISSUE THREAD

**Issue by fafaaye** [raniaamina/inkscape-splash-screen#5]

**Comment by layonaday** [comment]
Inkscape menampilkan dokumen baru (dokumen kosong) daripada file yang dipilih. Kalau di uninstall scriptnya, Inkscape tidak bisa dibuka. Bisa dibuka lewat terminal

**Comment by raniaamina** [comment]
Sudah diperbaiki oleh Pak @artemtech, silakan dicek kembali.
Terima kasih laporannya, Pak @layonaday, dan terima kasih Pull Request-nya Pak @artemtech.
